"""
Django settings for zoom_poc project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .base import *

SECRET_KEY = "bnpt6_xyuyygvet8z4m&q0@ffh^33w-ters%wo@x1^d=jxvu^-"
DEBUG = True
ALLOWED_HOSTS = []
